MODEL_ARGS=(
   --spec "slime_plugins.models.olmo3" "get_olmo3_spec"
   --transformer-impl local
   --swiglu
   --num-layers 32
   --hidden-size 4096
   --ffn-hidden-size 11008
   --num-attention-heads 32
   --group-query-attention
   --num-query-groups 32
   --max-position-embeddings 65536
   --use-rotary-position-embeddings
   --disable-bias-linear
   --normalization "RMSNorm"
   --norm-epsilon 1e-6
   --rotary-base 500000
   --vocab-size 100278
   --make-vocab-size-divisible-by 1
   --kv-channels 128
   --qk-layernorm
   --no-persist-layer-norm
   --use-rope-scaling
   --rotary-scaling-factor 8.0
   --no-rope-fusion
   --untie-embeddings-and-output-weights
)
