#!/usr/bin/env bash
# Resume the phase1 lambda075 E1M1 mixed run from step 59 for 160 more rollouts.
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
MIXED_ROOT="${LOYAL_MIXED_REPO_ROOT:-/cephfs/shared/experiment_g/loyal_agent_mixed_reward_ablation_v2}"
OLD_CKPT="${LOYAL_RESUME59_LOAD:-${MIXED_ROOT}/artifacts/checkpoints/mixed-v2-phase1-lambda075-e1m1-phase1-seed1234}"
NEW_CKPT="${LOYAL_RESUME59_SAVE:-/root/experiment_g_checkpoints/mixed-v2-phase1-lambda075-e1m1-resume59-plus160-seed1234}"

mkdir -p "${NEW_CKPT}"
cd "${PROJECT_ROOT}"

exec env \
  PATH="/root/experiment_g_runtime/conda/env/bin:${PATH}" \
  LOYAL_MODEL_ROOT="${LOYAL_MODEL_ROOT:-/cephfs/shared/experiment_g/assets/models}" \
  LOYAL_BASE_MODEL="${LOYAL_BASE_MODEL:-qwen3-4b}" \
  LOYAL_SHARED_CHECKPOINT_NAME="${LOYAL_SHARED_CHECKPOINT_NAME:-mixed-v2-phase1-lambda075-e1m1-resume59-plus160-seed1234}" \
  LOYAL_CHECKPOINT_HOST_DIR="${NEW_CKPT}" \
  LOYAL_MIXED_LOAD="${OLD_CKPT}" \
  LOYAL_MIXED_SAVE="${NEW_CKPT}" \
  LOYAL_MIXED_CKPT_STEP="${LOYAL_MIXED_CKPT_STEP:-59}" \
  LOYAL_MIXED_NUM_ROLLOUT="${LOYAL_MIXED_NUM_ROLLOUT:-220}" \
  LOYAL_MIXED_TRAIN_RECORDS="${LOYAL_MIXED_TRAIN_RECORDS:-${MIXED_ROOT}/artifacts/experiments/mixed_reward_ablation_phase1_parallel/phase1-lambda075-e1m1-phase1/mixed_train.jsonl}" \
  LOYAL_MIU_RECORDS="${LOYAL_MIU_RECORDS:-${MIXED_ROOT}/miu/data/dataset/MIU-v2/train.jsonl:${MIXED_ROOT}/miu/data/dataset/MIU-v2/val.jsonl}" \
  LOYAL_EIL_RECORDS="${LOYAL_EIL_RECORDS:-${MIXED_ROOT}/eil/data/dataset/EIL-v2/train.jsonl:${MIXED_ROOT}/eil/data/dataset/EIL-v2/val.jsonl}" \
  LOYAL_EIL_LEAKAGE_LAMBDA="${LOYAL_EIL_LEAKAGE_LAMBDA:-0.75}" \
  LOYAL_MIU_FAITHFULNESS_ETA="${LOYAL_MIU_FAITHFULNESS_ETA:-0.5}" \
  LOYAL_MIXED_EIL_BATCH_FRACTION="${LOYAL_MIXED_EIL_BATCH_FRACTION:-0.5}" \
  LOYAL_MIXED_GLOBAL_BATCH_SIZE="${LOYAL_MIXED_GLOBAL_BATCH_SIZE:-512}" \
  LOYAL_MIXED_ROLLOUT_BATCH_SIZE="${LOYAL_MIXED_ROLLOUT_BATCH_SIZE:-64}" \
  LOYAL_MIXED_SAMPLES_PER_PROMPT="${LOYAL_MIXED_SAMPLES_PER_PROMPT:-8}" \
  LOYAL_MIXED_MAX_RESPONSE_LEN="${LOYAL_MIXED_MAX_RESPONSE_LEN:-1024}" \
  LOYAL_MIXED_MAX_TOKENS_PER_GPU="${LOYAL_MIXED_MAX_TOKENS_PER_GPU:-4096}" \
  LOYAL_MIXED_LEARNING_RATE="${LOYAL_MIXED_LEARNING_RATE:-2e-7}" \
  LOYAL_MIXED_KL_LOSS_COEF="${LOYAL_MIXED_KL_LOSS_COEF:-0.05}" \
  LOYAL_MIXED_ENTROPY_COEF="${LOYAL_MIXED_ENTROPY_COEF:-0.002}" \
  LOYAL_MIXED_OPTIMIZER_CPU_OFFLOAD="${LOYAL_MIXED_OPTIMIZER_CPU_OFFLOAD:-0}" \
  LOYAL_MIXED_TRAIN_GPU_COUNT="${LOYAL_MIXED_TRAIN_GPU_COUNT:-2}" \
  LOYAL_MIXED_ROLLOUT_GPU_COUNT="${LOYAL_MIXED_ROLLOUT_GPU_COUNT:-2}" \
  LOYAL_MIXED_RAY_NUM_GPUS="${LOYAL_MIXED_RAY_NUM_GPUS:-4}" \
  LOYAL_MIXED_TRAIN_GPU_DEVICES="${LOYAL_MIXED_TRAIN_GPU_DEVICES:-0,1,2,3}" \
  CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0,1,2,3}" \
  LOYAL_MIXED_SGLANG_MEM_FRACTION_STATIC="${LOYAL_MIXED_SGLANG_MEM_FRACTION_STATIC:-0.78}" \
  LOYAL_MIXED_SGLANG_SERVER_CONCURRENCY="${LOYAL_MIXED_SGLANG_SERVER_CONCURRENCY:-64}" \
  LOYAL_MIXED_ENABLE_EVAL="${LOYAL_MIXED_ENABLE_EVAL:-0}" \
  LOYAL_MIXED_SAVE_INTERVAL="${LOYAL_MIXED_SAVE_INTERVAL:-20}" \
  LOYAL_RETAIN_ZERO_STD_GROUPS="${LOYAL_RETAIN_ZERO_STD_GROUPS:-1}" \
  LOYAL_JUDGE_CIRCUIT_ACTION="${LOYAL_JUDGE_CIRCUIT_ACTION:-soft_keep}" \
  LOYAL_RAY_TEMP_DIR="${LOYAL_RAY_TEMP_DIR:-/tmp/ray-resume59-plus160}" \
  LOYAL_RAY_DIRECT_DRIVER="${LOYAL_RAY_DIRECT_DRIVER:-1}" \
  LOYAL_RAY_STOP_BEFORE_START="${LOYAL_RAY_STOP_BEFORE_START:-1}" \
  LOYAL_USE_WANDB="${LOYAL_USE_WANDB:-0}" \
  bash scripts/launch/run_training_host.sh mixed
